Docker Build:
  before_script:
    # to skip default before_script
    - buildah info
    - buildah login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  stage: build
  image: quay.io/buildah/stable:latest
  script:
    - buildah build -t ${CI_REGISTRY_IMAGE}:latest
    - buildah push ${CI_REGISTRY_IMAGE}
